# Generated by Django 3.1.5 on 2021-01-26 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_management', '0002_methodology_steps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('type', models.SmallIntegerField(verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Entregável',
                'verbose_name_plural': 'Entregáveis',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('type', models.SmallIntegerField(verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.SmallIntegerField(verbose_name='Cargo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('status', models.SmallIntegerField(choices=[(1, 'Iniciado'), (2, 'Em Execução'), (3, 'Concluído'), (4, 'Inativo')], verbose_name='Status')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Data Registro')),
                ('programming_language', models.SmallIntegerField(choices=[(1, 'Java'), (2, 'Python'), (3, 'R'), (4, 'PHP')], verbose_name='Linguagem')),
                ('technology', models.CharField(max_length=150, verbose_name='Tecnologia')),
                ('technique', models.TextField(blank=True, null=True, verbose_name='Técnica')),
                ('data_source', models.CharField(max_length=150, verbose_name='Fonte Dados')),
                ('references', models.TextField(blank=True, null=True, verbose_name='Referências')),
                ('objective', models.CharField(max_length=250, verbose_name='Objetivo')),
                ('requester', models.CharField(max_length=150, verbose_name='Solicitante')),
                ('requester_sector', models.CharField(max_length=150, verbose_name='Setor do Solicitante')),
                ('deliverable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_management.deliverable')),
                ('feedback', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_management.feedback')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_management.person')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['id'],
            },
        ),
    ]
