# Generated by Django 3.1.5 on 2021-01-27 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0006_auto_20210127_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='methodology',
            name='step_8',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Etapa 7'),
        ),
    ]
