# Generated by Django 3.1.5 on 2021-01-28 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0007_methodology_step_8'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.CharField(default='teste', max_length=150, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(default=1, max_length=150, verbose_name='Sobrenome'),
            preserve_default=False,
        ),
    ]
