# Generated by Django 3.1.5 on 2021-01-28 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0009_auto_20210127_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='occupation',
            field=models.SmallIntegerField(choices=[(1, 'Desenvolvedor'), (2, 'Analista de Dados'), (3, 'Cientísta de Dados'), (4, 'Estatístico'), (5, 'Gerente de Projeto')], verbose_name='cARGO'),
        ),
    ]
