# Generated by Django 3.1.5 on 2021-02-03 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0010_auto_20210127_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deliverable',
            field=models.SmallIntegerField(choices=[(1, 'Planilha'), (2, 'Modelo matemático'), (3, 'Gráfico'), (4, 'API'), (5, 'Aplicação Web'), (6, 'População de Tabela/View')], default=1, verbose_name='Entregável'),
            preserve_default=False,
        ),
    ]
