# Generated by Django 3.1.5 on 2021-02-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0011_auto_20210202_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodologySteps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('description', models.CharField(max_length=250, verbose_name='Descrição')),
                ('steps', models.ManyToManyField(to='project_management.Steps')),
            ],
            options={
                'verbose_name': 'Metodologia',
                'verbose_name_plural': 'Metodologias',
            },
        ),
    ]
