# Generated by Django 3.1.5 on 2021-02-05 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0012_methodologysteps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='methodologysteps',
            options={'verbose_name': 'MetodologiaEtapa', 'verbose_name_plural': 'MetodologiaEtapas'},
        ),
    ]
