# Generated by Django 3.1.5 on 2021-02-05 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0014_auto_20210205_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nome')),
                ('order', models.SmallIntegerField(verbose_name='Ordem da Etapa')),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
            },
        ),
        migrations.DeleteModel(
            name='MethodologySteps',
        ),
        migrations.DeleteModel(
            name='StepsNew',
        ),
    ]
