# Generated by Django 3.1.5 on 2021-02-08 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0015_auto_20210205_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodologySteps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('description', models.CharField(max_length=250, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Metodologia',
                'verbose_name_plural': 'Metodologias',
            },
        ),
        migrations.AddField(
            model_name='steps',
            name='methodology',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='project_management.methodologysteps'),
            preserve_default=False,
        ),
    ]
