# Generated by Django 3.1.5 on 2021-02-25 16:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0016_auto_20210207_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_atualizacao',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data Última Atualização'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='methodology',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_management.methodologysteps'),
        ),
        migrations.AddField(
            model_name='project',
            name='step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_management.steps'),
        ),
    ]
