# Generated by Django 3.1.5 on 2021-03-31 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0019_projecthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='feedback',
            field=models.SmallIntegerField(choices=[(1, 'Aceito'), (2, 'Revisar'), (3, 'Rejeitado'), (4, 'Não consta')], default=4, verbose_name='Feedback'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
