# Generated by Django 3.1.5 on 2021-01-31 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210130_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(upload_to='user_profile/%self.id', verbose_name='Foto'),
        ),
    ]
