# Generated by Django 3.1.5 on 2021-01-31 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210131_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(upload_to='user_profile', verbose_name='Foto'),
        ),
    ]
